name: Build and publish

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-ios-app:
    name: Build iOS app
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
      - name: Set up Expo
        uses: expo/expo-github-action@v9
        with:
          eas-version: latest
          token: ${{secrets.EXPO_TOKEN}}
      - run: npm install
      - run: eas build -p ios --non-interactive --local
      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ${{ github.workspace }}/build-*.ipa
          retention-days: 30

  upload-ios-app:
    name: Upload iOS app
    needs: [build-ios-app]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
      - name: Set up Expo
        uses: expo/expo-github-action@v9
        with:
          eas-version: latest
          token: ${{secrets.EXPO_TOKEN}}
      - run: npm install
      - name: Download build artifact
        uses: actions/download-artifact@v8
        with:
          pattern: 'build-*.ipa'
      - run: eas submit -p ios --path build-*.ipa --profile production --non-interactive
        env:
          EXPO_APPLE_PASSWORD: ${{secrets.EXPO_APPLE_PASSWORD}}

  build-android-app:
    name: Build Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
      - name: Set up Expo
        uses: expo/expo-github-action@v9
        with:
          eas-version: latest
          token: ${{secrets.EXPO_TOKEN}}
      - run: npm install
      - run: eas build -p android --non-interactive --local
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=1g -Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" -Dorg.gradle.parallel=true -Dorg.gradle.daemon=false
      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ${{ github.workspace }}/build-*.apk
          retention-days: 30

  release:
    name: Create GitHub release
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    needs: [build-ios-app, build-android-app]
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v8
        with:
          pattern: build-*.apk
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: build-*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
